---
- name: Install and configure Filebeat 9.x
  hosts: filebeat
  become: yes
  tasks:
    - name: Install dependencies
      apt:
        name:
          - apt-transport-https
          - wget
        state: present
        update_cache: true

    - name: Add Elastic GPG key
      apt_key:
        url: https://artifacts.elastic.co/GPG-KEY-elasticsearch
        state: present

    - name: Add Elastic 9.x APT repository
      apt_repository:
        repo: "deb https://artifacts.elastic.co/packages/9.x/apt stable main"
        state: present
        filename: 'elastic-9.x'

    - name: Install Filebeat
      apt:
        name: filebeat
        state: present
        update_cache: true

    - name: Configure filebeat.yml
      copy:
        dest: /etc/filebeat/filebeat.yml
        owner: root
        group: root
        mode: '0644'
        content: |
          filebeat.inputs:
            - type: filestream
              id: all-logs
              enabled: true
              paths:
              {% for path in filebeat_inputs %}
                - {{ path }}
              {% endfor %}
              exclude_files: ['\.gz$']
              parsers:
                - multiline:
                    type: pattern
                    pattern: '^\['
                    negate: true
                    match: after

          output.logstash:
            hosts: ["{{ logstash_host }}:5044"]

          setup.template.enabled: false
          setup.ilm.enabled: false
          logging.to_files: true
          logging.files:
            path: /var/log/filebeat
            name: filebeat.log
            keepfiles: 7
            permissions: 0644

    - name: Enable and start Filebeat service
      systemd:
        name: filebeat
        enabled: yes
        state: restarted
